name-template: "v$RESOLVED_VERSION 🌈"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "🚀 Features"
    labels:
      - "enhancement"
  - title: "🛠 Improvements"
    label: "improvement"
  - title: "🐛 Bug Fixes"
    label: "bug"
  - title: "🧰 Maintenance"
    labels:
      - "chore"
      - "refactoring"
  - title: "⛓️ Dependency update"
    label: "dependencies"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "enhancement"
      - "improvement"
  patch:
    labels:
      - "patch"
  default: patch
template: |
  ## Changes
  $CHANGES

  ## Docker Images
  [ghcr.io/cosmo-workspace/cosmo-controller-manager:v$RESOLVED_VERSION](https://github.com/cosmo-workspace/cosmo/pkgs/container/cosmo-controller-manager)
  [ghcr.io/cosmo-workspace/cosmo-dashboard:v$RESOLVED_VERSION](https://github.com/cosmo-workspace/cosmo/pkgs/container/cosmo-dashboard)

  ## How to install

  See [GETTING-STARTED.md](https://github.com/cosmo-workspace/cosmo/blob/main/docs/GETTING-STARTED.md)

  ## How to upgrade

  ```sh
  # update helm local repository
  helm repo update

  # get current values for cosmo-controller-manager 
  helm get values cosmo-controller-manager -n cosmo-system | tail -n +2 > controller-manager.values.yaml

  # get current values for cosmo-dashboard
  helm get values cosmo-dashboard -n cosmo-system | tail -n +2 > dashboard.values.yaml

  # TODO: fix values.yaml if chart options is updated

  # upgrade cosmo-controller-manager
  helm upgrade cosmo-controller-manager cosmo/cosmo-controller-manager -n cosmo-system --values controller-manager.values.yaml

  # upgrade cosmo-dashboard
  helm upgrade cosmo-dashboard cosmo/cosmo-dashboard -n cosmo-system --values dashboard.values.yaml
  ```
