name-template: "v$RESOLVED_VERSION 🌈"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "🚀 Features"
    labels:
      - "enhancement"
  - title: "🛠 Improvements"
    label: "improvement"
  - title: "🐛 Bug Fixes"
    label: "bug"
  - title: "🧰 Maintenance"
    labels:
      - "chore"
      - "refactoring"
  - title: "⛓️ Dependency update"
    label: "dependencies"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
template: |
  ## Changes from $PREVIOUS_TAG
  $CHANGES

  ## Docker Images
  [ghcr.io/cosmo-workspace/cosmo-controller-manager:v$RESOLVED_VERSION](https://github.com/cosmo-workspace/cosmo/pkgs/container/cosmo-controller-manager)
  [ghcr.io/cosmo-workspace/cosmo-dashboard:v$RESOLVED_VERSION](https://github.com/cosmo-workspace/cosmo/pkgs/container/cosmo-dashboard)
  [ghcr.io/cosmo-workspace/cosmo-traefik-plugins:v$RESOLVED_VERSION](https://github.com/cosmo-workspace/cosmo/pkgs/container/cosmo-traefik-plugins)

  ## How to install

  See [GETTING-STARTED.md](https://github.com/cosmo-workspace/cosmo/blob/main/docs/GETTING-STARTED.md)

  ## How to upgrade

  ```sh
  # update helm local repository
  helm repo update

  # get current values
  helm get values cosmo -n cosmo-system | tail -n +2 > current.values.yaml

  # TODO: fix values.yaml if chart options is updated

  # upgrade cosmo
  helm upgrade cosmo cosmo/cosmo -n cosmo-system --values new.values.yaml
  ```
