AWSTemplateFormatVersion: "2010-09-09"
Description: EKS IAM Role for ServiceAccount

Resources:
  IAMRoleForServiceAccount:
    Type: AWS::IAM::Role
    Properties: 
      RoleName: COSMOUserIRSARole
      Description: EKS IAM Role for ServiceAccount
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/AWSCodeCommitPowerUser
      AssumeRolePolicyDocument:
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Principal": {
                "Federated": !Sub "arn:aws:iam::${AWS::AccountId}:oidc-provider/OIDC_PROVIDER"
              },
              "Action": "sts:AssumeRoleWithWebIdentity",
              "Condition": {
                "StringLike": {
                  "OIDC_PROVIDER:sub": "system:serviceaccount:cosmo-user-*:default"
                }
              }
            }
          ]
        }