apiVersion: cosmo-workspace.github.io/v1alpha1
kind: Template
metadata:
  annotations:
    cosmo-workspace.github.io/disable-nameprefix: "true"
  labels:
    cosmo-workspace.github.io/type: useraddon
  name: eks-irsa
spec:
  description: UserAddon to associate ServiceAccount with IAM Role
  rawYaml: |
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/IAM_ROLE_NAME
      name: default
      namespace: '{{NAMESPACE}}'
