---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1alpha1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-cosmo-workspace-github-io-v1alpha1-instance
  failurePolicy: Fail
  name: minstance.kb.io
  rules:
  - apiGroups:
    - cosmo-workspace.github.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - instances
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1alpha1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-cosmo-workspace-github-io-v1alpha1-instance
  failurePolicy: Fail
  name: mclusterinstance.kb.io
  rules:
  - apiGroups:
    - cosmo-workspace.github.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clusterinstances
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1alpha1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-cosmo-workspace-github-io-v1alpha1-user
  failurePolicy: Fail
  name: muser.kb.io
  rules:
  - apiGroups:
    - cosmo-workspace.github.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - users
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1alpha1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-cosmo-workspace-github-io-v1alpha1-workspace
  failurePolicy: Fail
  name: mworkspace.kb.io
  rules:
  - apiGroups:
    - cosmo-workspace.github.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - workspaces
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1alpha1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-cosmo-workspace-github-io-v1alpha1-instance
  failurePolicy: Fail
  name: vclusterinstance.kb.io
  rules:
  - apiGroups:
    - cosmo-workspace.github.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clusterinstances
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1alpha1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-cosmo-workspace-github-io-v1alpha1-instance
  failurePolicy: Fail
  name: vinstance.kb.io
  rules:
  - apiGroups:
    - cosmo-workspace.github.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - instances
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1alpha1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-cosmo-workspace-github-io-v1alpha1-user
  failurePolicy: Fail
  name: vuser.kb.io
  rules:
  - apiGroups:
    - cosmo-workspace.github.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - users
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1alpha1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-cosmo-workspace-github-io-v1alpha1-workspace
  failurePolicy: Fail
  name: vworkspace.kb.io
  rules:
  - apiGroups:
    - cosmo-workspace.github.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - workspaces
  sideEffects: None
