apiVersion: cosmo-workspace.github.io/v1alpha1
kind: ClusterTemplate
metadata:
  annotations:
    cosmo-workspace.github.io/disable-nameprefix: "true"
  labels:
    cosmo-workspace.github.io/type: useraddon
  name: efs-shared-filesystem
spec:
  description: UserAddon to create volumes associated with Amazon EFS filesystem fixed path
  requiredVars:
    - var: EFS_FILESYSTEM_ID
      default: fs-4af69aab
  rawYaml: |
    apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: 'efs-{{USER_NAME}}'
    provisioner: efs.csi.aws.com
    ---
    apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: 'efs-{{USER_NAME}}'
    spec:
      accessModes:
      - ReadWriteMany
      capacity:
        storage: 5Gi
      csi:
        driver: efs.csi.aws.com
        volumeHandle: "{{EFS_FILESYSTEM_ID}}"
      persistentVolumeReclaimPolicy: Retain
      storageClassName: 'efs-{{USER_NAME}}'
      volumeMode: Filesystem
    ---
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: 'shared-efs-pvc'
      namespace: '{{NAMESPACE}}'
    spec:
      accessModes:
      - ReadWriteMany
      resources:
        requests:
          storage: 5Gi
      storageClassName: 'efs-{{USER_NAME}}'
