/*
 * Cosmo Dashboard API
 *
 * Manipulate cosmo dashboard resource API
 *
 * API version: v1alpha1
 * Contact: jlandowner8@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1alpha1

type PatchWorkspaceRequest struct {
	Replicas *int64 `json:"replicas,omitempty"`
}

// AssertPatchWorkspaceRequestRequired checks if the required fields are not zero-ed
func AssertPatchWorkspaceRequestRequired(obj PatchWorkspaceRequest) error {
	return nil
}

// AssertRecursePatchWorkspaceRequestRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of PatchWorkspaceRequest (e.g. [][]PatchWorkspaceRequest), otherwise ErrTypeAssertionError is thrown.
func AssertRecursePatchWorkspaceRequestRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aPatchWorkspaceRequest, ok := obj.(PatchWorkspaceRequest)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertPatchWorkspaceRequestRequired(aPatchWorkspaceRequest)
	})
}
