/*
 * Cosmo Dashboard API
 *
 * Manipulate cosmo dashboard resource API
 *
 * API version: v1alpha1
 * Contact: jlandowner8@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1alpha1

type PatchWorkspaceResponse struct {
	Message string `json:"message"`

	Workspace *Workspace `json:"workspace"`
}

// AssertPatchWorkspaceResponseRequired checks if the required fields are not zero-ed
func AssertPatchWorkspaceResponseRequired(obj PatchWorkspaceResponse) error {
	elements := map[string]interface{}{
		"message":   obj.Message,
		"workspace": obj.Workspace,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if obj.Workspace != nil {
		if err := AssertWorkspaceRequired(*obj.Workspace); err != nil {
			return err
		}
	}
	return nil
}

// AssertRecursePatchWorkspaceResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of PatchWorkspaceResponse (e.g. [][]PatchWorkspaceResponse), otherwise ErrTypeAssertionError is thrown.
func AssertRecursePatchWorkspaceResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aPatchWorkspaceResponse, ok := obj.(PatchWorkspaceResponse)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertPatchWorkspaceResponseRequired(aPatchWorkspaceResponse)
	})
}
