/*
 * Cosmo Dashboard API
 *
 * Manipulate cosmo dashboard resource API
 *
 * API version: v1alpha1
 * Contact: jlandowner8@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1alpha1

type UpdateUserRoleRequest struct {
	Role string `json:"role,omitempty"`
}

// AssertUpdateUserRoleRequestRequired checks if the required fields are not zero-ed
func AssertUpdateUserRoleRequestRequired(obj UpdateUserRoleRequest) error {
	return nil
}

// AssertRecurseUpdateUserRoleRequestRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of UpdateUserRoleRequest (e.g. [][]UpdateUserRoleRequest), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseUpdateUserRoleRequestRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aUpdateUserRoleRequest, ok := obj.(UpdateUserRoleRequest)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertUpdateUserRoleRequestRequired(aUpdateUserRoleRequest)
	})
}
