/*
 * Cosmo Dashboard API
 *
 * Manipulate cosmo dashboard resource API
 *
 * API version: v1alpha1
 * Contact: jlandowner8@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1alpha1

type RemoveNetworkRuleResponse struct {
	Message string `json:"message"`

	NetworkRule NetworkRule `json:"networkRule"`
}

// AssertRemoveNetworkRuleResponseRequired checks if the required fields are not zero-ed
func AssertRemoveNetworkRuleResponseRequired(obj RemoveNetworkRuleResponse) error {
	elements := map[string]interface{}{
		"message":     obj.Message,
		"networkRule": obj.NetworkRule,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertNetworkRuleRequired(obj.NetworkRule); err != nil {
		return err
	}
	return nil
}

// AssertRecurseRemoveNetworkRuleResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of RemoveNetworkRuleResponse (e.g. [][]RemoveNetworkRuleResponse), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseRemoveNetworkRuleResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aRemoveNetworkRuleResponse, ok := obj.(RemoveNetworkRuleResponse)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertRemoveNetworkRuleResponseRequired(aRemoveNetworkRuleResponse)
	})
}
