/*
 * Cosmo Dashboard API
 *
 * Manipulate cosmo dashboard resource API
 *
 * API version: v1alpha1
 * Contact: jlandowner8@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1alpha1

type UpdateUserNameResponse struct {
	Message string `json:"message"`

	User *User `json:"user"`
}

// AssertUpdateUserNameResponseRequired checks if the required fields are not zero-ed
func AssertUpdateUserNameResponseRequired(obj UpdateUserNameResponse) error {
	elements := map[string]interface{}{
		"message": obj.Message,
		"user":    obj.User,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if obj.User != nil {
		if err := AssertUserRequired(*obj.User); err != nil {
			return err
		}
	}
	return nil
}

// AssertRecurseUpdateUserNameResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of UpdateUserNameResponse (e.g. [][]UpdateUserNameResponse), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseUpdateUserNameResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aUpdateUserNameResponse, ok := obj.(UpdateUserNameResponse)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertUpdateUserNameResponseRequired(aUpdateUserNameResponse)
	})
}
