/*
 * Cosmo Dashboard API
 *
 * Manipulate cosmo dashboard resource API
 *
 * API version: v1alpha1
 * Contact: jlandowner8@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1alpha1

type CreateWorkspaceRequest struct {
	Name string `json:"name"`

	Template string `json:"template"`

	Vars map[string]string `json:"vars,omitempty"`
}

// AssertCreateWorkspaceRequestRequired checks if the required fields are not zero-ed
func AssertCreateWorkspaceRequestRequired(obj CreateWorkspaceRequest) error {
	elements := map[string]interface{}{
		"name":     obj.Name,
		"template": obj.Template,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseCreateWorkspaceRequestRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of CreateWorkspaceRequest (e.g. [][]CreateWorkspaceRequest), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseCreateWorkspaceRequestRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aCreateWorkspaceRequest, ok := obj.(CreateWorkspaceRequest)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertCreateWorkspaceRequestRequired(aCreateWorkspaceRequest)
	})
}
