/*
 * Cosmo Dashboard API
 *
 * Manipulate cosmo dashboard resource API
 *
 * API version: v1alpha1
 * Contact: jlandowner8@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1alpha1

type ErrorResponse struct {
	Message string `json:"message,omitempty"`
}

// AssertErrorResponseRequired checks if the required fields are not zero-ed
func AssertErrorResponseRequired(obj ErrorResponse) error {
	return nil
}

// AssertRecurseErrorResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ErrorResponse (e.g. [][]ErrorResponse), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseErrorResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aErrorResponse, ok := obj.(ErrorResponse)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertErrorResponseRequired(aErrorResponse)
	})
}
