/*
 * Cosmo Dashboard API
 *
 * Manipulate cosmo dashboard resource API
 *
 * API version: v1alpha1
 * Contact: jlandowner8@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1alpha1

type WorkspaceStatus struct {
	Phase string `json:"phase"`

	MainUrl string `json:"mainUrl,omitempty"`

	UrlBase string `json:"urlBase,omitempty"`
}

// AssertWorkspaceStatusRequired checks if the required fields are not zero-ed
func AssertWorkspaceStatusRequired(obj WorkspaceStatus) error {
	elements := map[string]interface{}{
		"phase": obj.Phase,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseWorkspaceStatusRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of WorkspaceStatus (e.g. [][]WorkspaceStatus), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseWorkspaceStatusRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aWorkspaceStatus, ok := obj.(WorkspaceStatus)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertWorkspaceStatusRequired(aWorkspaceStatus)
	})
}
