/*
 * Cosmo Dashboard API
 *
 * Manipulate cosmo dashboard resource API
 *
 * API version: v1alpha1
 * Contact: jlandowner8@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1alpha1

type UpdateUserPasswordResponse struct {
	Message string `json:"message"`
}

// AssertUpdateUserPasswordResponseRequired checks if the required fields are not zero-ed
func AssertUpdateUserPasswordResponseRequired(obj UpdateUserPasswordResponse) error {
	elements := map[string]interface{}{
		"message": obj.Message,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseUpdateUserPasswordResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of UpdateUserPasswordResponse (e.g. [][]UpdateUserPasswordResponse), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseUpdateUserPasswordResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aUpdateUserPasswordResponse, ok := obj.(UpdateUserPasswordResponse)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertUpdateUserPasswordResponseRequired(aUpdateUserPasswordResponse)
	})
}
