/*
 * Cosmo Dashboard API
 *
 * Manipulate cosmo dashboard resource API
 *
 * API version: v1alpha1
 * Contact: jlandowner8@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1alpha1

type CreateWorkspaceResponse struct {
	Message string `json:"message"`

	Workspace *Workspace `json:"workspace"`
}

// AssertCreateWorkspaceResponseRequired checks if the required fields are not zero-ed
func AssertCreateWorkspaceResponseRequired(obj CreateWorkspaceResponse) error {
	elements := map[string]interface{}{
		"message":   obj.Message,
		"workspace": obj.Workspace,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if obj.Workspace != nil {
		if err := AssertWorkspaceRequired(*obj.Workspace); err != nil {
			return err
		}
	}
	return nil
}

// AssertRecurseCreateWorkspaceResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of CreateWorkspaceResponse (e.g. [][]CreateWorkspaceResponse), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseCreateWorkspaceResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aCreateWorkspaceResponse, ok := obj.(CreateWorkspaceResponse)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertCreateWorkspaceResponseRequired(aCreateWorkspaceResponse)
	})
}
