/*
 * Cosmo Dashboard API
 *
 * Manipulate cosmo dashboard resource API
 *
 * API version: v1alpha1
 * Contact: jlandowner8@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1alpha1

type ListTemplatesResponse struct {
	Message string `json:"message,omitempty"`

	Items []Template `json:"items"`
}

// AssertListTemplatesResponseRequired checks if the required fields are not zero-ed
func AssertListTemplatesResponseRequired(obj ListTemplatesResponse) error {
	elements := map[string]interface{}{
		"items": obj.Items,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Items {
		if err := AssertTemplateRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertRecurseListTemplatesResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ListTemplatesResponse (e.g. [][]ListTemplatesResponse), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseListTemplatesResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aListTemplatesResponse, ok := obj.(ListTemplatesResponse)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertListTemplatesResponseRequired(aListTemplatesResponse)
	})
}
