/*
 * Cosmo Dashboard API
 *
 * Manipulate cosmo dashboard resource API
 *
 * API version: v1alpha1
 * Contact: jlandowner8@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1alpha1

type UpdateUserNameRequest struct {
	DisplayName string `json:"displayName"`
}

// AssertUpdateUserNameRequestRequired checks if the required fields are not zero-ed
func AssertUpdateUserNameRequestRequired(obj UpdateUserNameRequest) error {
	elements := map[string]interface{}{
		"displayName": obj.DisplayName,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseUpdateUserNameRequestRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of UpdateUserNameRequest (e.g. [][]UpdateUserNameRequest), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseUpdateUserNameRequestRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aUpdateUserNameRequest, ok := obj.(UpdateUserNameRequest)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertUpdateUserNameRequestRequired(aUpdateUserNameRequest)
	})
}
