apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: auth-proxy-role
rules:
  - apiGroups:
      - cosmo-workspace.github.io
    resources:
      - instances
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - cosmo-workspace.github.io
    resources:
      - instances/status
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: auth-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: auth-proxy-role
subjects:
  - kind: ServiceAccount
    name: default
