# permissions for end users to edit instances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: instance-editor-role
rules:
  - apiGroups:
      - cosmo-workspace.github.io
    resources:
      - instances
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - cosmo-workspace.github.io
    resources:
      - instances/status
    verbs:
      - get
