apiVersion: v1
data:
  controller_manager_config.yaml: |
    apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
    kind: ControllerManagerConfig
    health:
      healthProbeBindAddress: :{{ .Values.healthzPort }}
    {{- if .Values.metrics.enabled }}
    metrics:
      bindAddress: 127.0.0.1:{{ .Values.metrics.port }}
    {{- end }}
    webhook:
      port: {{ .Values.webhookPort }}
    leaderElection:
      leaderElect: true
      resourceName: 04c57811.cosmo-workspace.github.io
kind: ConfigMap
metadata:
  labels:
    {{- include "cosmo-controller-manager.labels" . | nindent 4 }}
  name: cosmo-manager-config
  namespace: {{ .Release.Namespace }}
---
{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "cosmo-controller-manager.labels" . | nindent 4 }}
  name: cosmo-controller-manager-metrics-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: https
    port: {{ .Values.metrics.kubeRbacProxy.port }}
    targetPort: {{ if .Values.metrics.kubeRbacProxy.enabled -}}{{ .Values.metrics.kubeRbacProxy.port }}{{- else -}}{{ .Values.metrics.port }}{{ end }}
  selector:
    {{- include "cosmo-controller-manager.selectorLabels" . | nindent 4 }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "cosmo-controller-manager.labels" . | nindent 4 }}
  name: cosmo-webhook-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 443
    targetPort: {{ .Values.webhookPort }}
  {{- if not .Values.localRunTest.enabled }}
  selector:
    {{- include "cosmo-controller-manager.selectorLabels" . | nindent 4 }}
  {{- end }}
---
{{- if .Values.localRunTest.enabled }}
apiVersion: v1
kind: Endpoints
metadata:
  labels:
    {{- include "cosmo-controller-manager.labels" . | nindent 4 }}
  name: cosmo-webhook-service
  namespace: {{ .Release.Namespace }}
subsets:
- addresses:
  - ip: {{ .Values.localRunTest.webhookEndpoint.ip }}
  ports:
  - port: {{ .Values.localRunTest.webhookEndpoint.port }}
    protocol: TCP
---
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "cosmo-controller-manager.labels" . | nindent 4 }}
  name: cosmo-controller-manager
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "cosmo-controller-manager.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cosmo-controller-manager.selectorLabels" . | nindent 8 }}
        {{- if .Values.podLabels }}
        {{- toYaml .Values.podLabels | nindent 8 }}
        {{- end }}
      {{- if .Values.podAnnotations }}
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
      {{- end }}
    spec:
      containers:
      - args:
        - --port={{ .Values.webhookPort }}
        - --health-probe-bind-address=:{{ .Values.healthzPort }}
        {{- if and (.Values.metrics.enabled) (.Values.metrics.kubeRbacProxy.enabled) }}
        - --metrics-bind-address=127.0.0.1:{{ $.Values.metrics.port }}
        {{- else if and (.Values.metrics.enabled) (not .Values.metrics.kubeRbacProxy.enabled) }}
        - --metrics-bind-address=0.0.0.0:{{ $.Values.metrics.port }}
        {{- else }}
        - --metrics-bind-address=0
        {{- end }}
        - --leader-elect
        - --zap-log-level={{ .Values.logLevel }}
        - --zap-time-encoding={{ .Values.logTimeEncoding }}
        {{- if ne .Values.logLevel "info" }}
        - --zap-devel=true
        {{- end }}
        {{- if .Values.traefik.entrypoints }}
        - --traefik-entrypoints={{ join "," .Values.traefik.entrypoints }}
        {{- end }}
        {{- if .Values.traefik.middlewares.auth }}
        - --traefik-authen-middleware={{ .Values.traefik.middlewares.auth }}
        {{- end }}
        {{- if .Values.traefik.namespace }}
        - --traefik-authen-middleware-namespace={{ .Values.traefik.namespace }}
        {{- else }}
        - --traefik-authen-middleware-namespace={{ .Release.Namespace }}
        {{- end }}
        {{- if .Values.traefik.middlewares.usernameHeader }}
        - --traefik-username-header-middleware={{ .Values.traefik.middlewares.usernameHeader }}
        {{- end }}
        - --workspace-urlbase-protocol={{ .Values.defaultURLBase.protocol }}
        - --workspace-urlbase-host={{ .Values.defaultURLBase.host }}
        - --workspace-urlbase-domain={{ .Values.defaultURLBase.domain }}
        command:
        - /manager
        image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.healthzPort }}
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        ports:
        - containerPort: {{ .Values.webhookPort }}
          name: webhook-server
          protocol: TCP
        {{- if and (.Values.metrics.enabled) (not .Values.metrics.kubeRbacProxy.enabled) }}
        - containerPort: {{ .Values.metrics.port }}
          name: metrics
          protocol: TCP
        {{- end }}
        readinessProbe:
          httpGet:
            path: /readyz
            port: {{ .Values.healthzPort }}
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
      {{- if and (.Values.metrics.enabled) (.Values.metrics.kubeRbacProxy.enabled) }}
      - args:
        - --secure-listen-address=0.0.0.0:{{ .Values.metrics.kubeRbacProxy.port }}
        - --upstream=http://127.0.0.1:{{ .Values.metrics.port }}/
        - --logtostderr=true
        - --v=10
        image: {{ .Values.metrics.kubeRbacProxy.image.repository }}:{{ .Values.metrics.kubeRbacProxy.image.tag }}
        imagePullPolicy: {{ .Values.metrics.kubeRbacProxy.image.pullPolicy }}
        name: kube-rbac-proxy
        ports:
        - containerPort: {{ .Values.metrics.kubeRbacProxy.port }}
          name: https
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
      {{- end }}
      {{- if .Values.hostNetwork }}
      hostNetwork: true
      {{- end }}
      {{- if .Values.dnsPolicy }}
      dnsPolicy: {{ .Values.dnsPolicy }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "cosmo-controller-manager.serviceAccountName" . }}
      terminationGracePeriodSeconds: 10
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: webhook-server-cert
