apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- workspace.yaml
- network.yaml

images:
- name: codercom/code-server
  newName: cosmo.io:5000/my-code-server
  newTag: latest
