apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: cosmo-username-headers
spec:
  headers:
    customRequestHeaders:
      X-Cosmo-UserName: "{{USER_NAME}}"
      X-Cosmo-UserName-{{USER_NAME}}: "1"
    customResponseHeaders:
      X-Cosmo-UserName: "{{USER_NAME}}"
