{{ $tls := fromYaml ( include "cosmo.webhook.gen-certs" . ) }}
---
{{- if not $.Values.certManager.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: webhook-server-cert
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cosmo.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  ca.crt: {{ $tls.caCert }}
  tls.crt: {{ $tls.clientCert }}
  tls.key: {{ $tls.clientKey }}
{{- else }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    {{- include "cosmo.labels" . | nindent 4 }}
  name: cosmo-webhook-cert
  namespace: {{ .Release.Namespace }}
spec:
  dnsNames:
  - cosmo-webhook-service.{{ .Release.Namespace }}.svc
  - cosmo-webhook-service.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    {{- if .Values.certManager.issuer.clusterIssuer }}
    kind: ClusterIssuer
    {{- else }}
    kind: Issuer
    namespace: {{ .Values.certManager.issuer.namespace | default .Release.Namespace }}
    {{- end }}
    name: {{ .Values.certManager.issuer.name }}
  secretName: webhook-server-cert
{{- end }}
