{{ $tls := fromYaml ( include "cosmo.webhook.gen-certs" . ) }}
---
{{- if $.Values.controllerManager.webhook.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
{{- if $.Values.certManager.enabled }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/cosmo-webhook-cert
  {{- end }}
  labels:
    {{- include "cosmo.labels" . | nindent 4 }}
  name: cosmo-mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1alpha1
  clientConfig:
    caBundle: {{ if not $.Values.certManager.enabled -}}{{ $tls.caCert }}{{- else -}}Cg=={{ end }}
    service:
      name: cosmo-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /mutate-cosmo-workspace-github-io-v1alpha1-instance
  failurePolicy: Fail
  name: mclusterinstance.kb.io
  rules:
  - apiGroups:
    - cosmo-workspace.github.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clusterinstances
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1alpha1
  clientConfig:
    caBundle: {{ if not $.Values.certManager.enabled -}}{{ $tls.caCert }}{{- else -}}Cg=={{ end }}
    service:
      name: cosmo-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /mutate-cosmo-workspace-github-io-v1alpha1-instance
  failurePolicy: Fail
  name: minstance.kb.io
  rules:
  - apiGroups:
    - cosmo-workspace.github.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - instances
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1alpha1
  clientConfig:
    caBundle: {{ if not $.Values.certManager.enabled -}}{{ $tls.caCert }}{{- else -}}Cg=={{ end }}
    service:
      name: cosmo-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /mutate-cosmo-workspace-github-io-v1alpha1-user
  failurePolicy: Fail
  name: muser.kb.io
  rules:
  - apiGroups:
    - cosmo-workspace.github.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - users
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1alpha1
  clientConfig:
    caBundle: {{ if not $.Values.certManager.enabled -}}{{ $tls.caCert }}{{- else -}}Cg=={{ end }}
    service:
      name: cosmo-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /mutate-cosmo-workspace-github-io-v1alpha1-workspace
  failurePolicy: Fail
  name: mworkspace.kb.io
  rules:
  - apiGroups:
    - cosmo-workspace.github.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - workspaces
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
{{- if $.Values.certManager.enabled }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/cosmo-webhook-cert
  {{- end }}
  labels:
    {{- include "cosmo.labels" . | nindent 4 }}
  name: cosmo-validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1alpha1
  clientConfig:
    caBundle: {{ if not $.Values.certManager.enabled -}}{{ $tls.caCert }}{{- else -}}Cg=={{ end }}
    service:
      name: cosmo-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /validate-cosmo-workspace-github-io-v1alpha1-instance
  failurePolicy: Fail
  name: vclusterinstance.kb.io
  rules:
  - apiGroups:
    - cosmo-workspace.github.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clusterinstances
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1alpha1
  clientConfig:
    caBundle: {{ if not $.Values.certManager.enabled -}}{{ $tls.caCert }}{{- else -}}Cg=={{ end }}
    service:
      name: cosmo-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /validate-cosmo-workspace-github-io-v1alpha1-template
  failurePolicy: Fail
  name: vclustertemplate.kb.io
  rules:
  - apiGroups:
    - cosmo-workspace.github.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clustertemplates
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1alpha1
  clientConfig:
    caBundle: {{ if not $.Values.certManager.enabled -}}{{ $tls.caCert }}{{- else -}}Cg=={{ end }}
    service:
      name: cosmo-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /validate-cosmo-workspace-github-io-v1alpha1-instance
  failurePolicy: Fail
  name: vinstance.kb.io
  rules:
  - apiGroups:
    - cosmo-workspace.github.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - instances
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1alpha1
  clientConfig:
    caBundle: {{ if not $.Values.certManager.enabled -}}{{ $tls.caCert }}{{- else -}}Cg=={{ end }}
    service:
      name: cosmo-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /validate-cosmo-workspace-github-io-v1alpha1-template
  failurePolicy: Fail
  name: vtemplate.kb.io
  rules:
  - apiGroups:
    - cosmo-workspace.github.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - templates
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1alpha1
  clientConfig:
    caBundle: {{ if not $.Values.certManager.enabled -}}{{ $tls.caCert }}{{- else -}}Cg=={{ end }}
    service:
      name: cosmo-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /validate-cosmo-workspace-github-io-v1alpha1-user
  failurePolicy: Fail
  name: vuser.kb.io
  rules:
  - apiGroups:
    - cosmo-workspace.github.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - users
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1alpha1
  clientConfig:
    caBundle: {{ if not $.Values.certManager.enabled -}}{{ $tls.caCert }}{{- else -}}Cg=={{ end }}
    service:
      name: cosmo-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /validate-cosmo-workspace-github-io-v1alpha1-workspace
  failurePolicy: Fail
  name: vworkspace.kb.io
  rules:
  - apiGroups:
    - cosmo-workspace.github.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - workspaces
  sideEffects: None
{{- end }}
