apiVersion: cosmo-workspace.github.io/v1alpha1
kind: Template
metadata:
  annotations:
    workspace.cosmo-workspace.github.io/deployment: code-server
    workspace.cosmo-workspace.github.io/service: code-server
    workspace.cosmo-workspace.github.io/service-main-port: http
  labels:
    cosmo-workspace.github.io/type: workspace
  name: code-server-example
spec:
  description: Example Workspace Template for code-server
  rawYaml: |
    apiVersion: v1
    kind: Service
    metadata:
      labels:
        app.kubernetes.io/instance: code-server
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: code-server
        cosmo-workspace.github.io/instance: '{{INSTANCE}}'
        cosmo-workspace.github.io/template: '{{TEMPLATE}}'
        helm.sh/chart: code-server-1.0.5
      name: '{{INSTANCE}}-code-server'
      namespace: '{{NAMESPACE}}'
    spec:
      ports:
      - name: http
        port: 8080
        protocol: TCP
        targetPort: http
      selector:
        app.kubernetes.io/instance: code-server
        app.kubernetes.io/name: code-server
        cosmo-workspace.github.io/instance: '{{INSTANCE}}'
        cosmo-workspace.github.io/template: '{{TEMPLATE}}'
      type: ClusterIP
    ---
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app.kubernetes.io/instance: code-server
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: code-server
        cosmo-workspace.github.io/instance: '{{INSTANCE}}'
        cosmo-workspace.github.io/template: '{{TEMPLATE}}'
        helm.sh/chart: code-server-1.0.5
      name: '{{INSTANCE}}-code-server'
      namespace: '{{NAMESPACE}}'
    spec:
      replicas: 1
      selector:
        matchLabels:
          app.kubernetes.io/instance: code-server
          app.kubernetes.io/name: code-server
          cosmo-workspace.github.io/instance: '{{INSTANCE}}'
          cosmo-workspace.github.io/template: '{{TEMPLATE}}'
      strategy:
        type: Recreate
      template:
        metadata:
          labels:
            app.kubernetes.io/instance: code-server
            app.kubernetes.io/name: code-server
            cosmo-workspace.github.io/instance: '{{INSTANCE}}'
            cosmo-workspace.github.io/template: '{{TEMPLATE}}'
        spec:
          containers:
          - args:
            - --auth=none
            image: codercom/code-server:3.12.0
            imagePullPolicy: Always
            livenessProbe:
              httpGet:
                path: /
                port: http
            name: code-server
            ports:
            - containerPort: 8080
              name: http
              protocol: TCP
            readinessProbe:
              httpGet:
                path: /
                port: http
            resources: {}
            securityContext:
              runAsUser: 1000
            volumeMounts:
            - mountPath: /home/coder
              name: data
          initContainers:
          - command:
            - sh
            - -c
            - |
              chown -R 1000:1000 /home/coder
            image: busybox:latest
            imagePullPolicy: IfNotPresent
            name: init-chmod-data
            securityContext:
              runAsUser: 0
            volumeMounts:
            - mountPath: /home/coder
              name: data
          securityContext:
            fsGroup: 1000
          serviceAccountName: default
          volumes:
          - name: data
            emptyDir: {}
