/* tslint:disable */
/* eslint-disable */
/**
 * Cosmo Dashboard API
 * Manipulate cosmo dashboard resource API
 *
 * The version of the OpenAPI document: v1alpha1
 * Contact: jlandowner8@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

