apiVersion: v1
kind: Secret
metadata:
  name: cosmo-auth-env
  namespace: "{{ .Release.Namespace }}"
stringData:
  COOKIE_DOMAIN: "{{ .Values.domain }}"
  COOKIE_HASHKEY: "{{ randAlphaNum 64 }}"
  COOKIE_BLOCKKEY: "{{ randAlphaNum 32 }}"
  COOKIE_SESSION_NAME: "{{ randAlphaNum 10 }}"
  SIGNIN_URL: "{{ .Values.cosmoAuth.signinUrl }}"
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: cosmo-auth
  namespace: "{{ .Release.Namespace }}"
spec:
  plugin:
    cosmoauth:
      logLevel: DEBUG
      cookieSessionName: "${COOKIE_SESSION_NAME}"
      cookieDomain: "${COOKIE_DOMAIN}"
      cookieHashKey: "${COOKIE_HASHKEY}"
      cookieBlockKey: "${COOKIE_BLOCKKEY}"
      signInUrl: "${SIGNIN_URL}"
