apiVersion: v1
kind: Service
metadata:
  name: workspace
spec:
  type: ClusterIP
  ports:
    - name: main
      port: 18080
      protocol: TCP
---
#
# IngressRoute
#
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: workspace
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: "Host(`main-{{INSTANCE}}-{{USER_NAME}}-k3d.domain`)"
      priority: 10
      services:
        - name: "{{INSTANCE}}-workspace"
          port: main
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: workspace
# spec:
#   ingressClassName: traefik
#   rules:
#     - host: main-{{INSTANCE}}-{{USER_NAME}}-k3d.domain
#       http:
#         paths:
#           - backend:
#               service:
#                 name: workspace
#                 port:
#                   name: main
#             path: /
#             pathType: Prefix
