apiVersion: v1
kind: Service
metadata:
  name: workspace
  annotations:
    cosmo-workspace.github.io/delete-policy: keep
spec:
  type: ClusterIP
  ports:
    - name: main
      port: 18080
      protocol: TCP
